version: "3"
services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongopassword
      - MONGO_INITDB_DATABASE=mongo
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGOUSER=mongo
      - MONGOPASSWORD=mongopassword
      - MONGODATABASE=mongo
      - MONGOPORT=27017
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    environment:
      - WDS_SOCKET_PORT=0
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "8080:80"
